name: Dependency Scan

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to scan'
        required: true
        default: 'main'

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}
          fetch-depth: 0
          
      - name: Dependency Review vs Main
        uses: actions/dependency-review-action@v4
        with:
          base-ref: 'main'
          head-ref: ${{ github.event.inputs.branch_name }}
          
